openapi: 3.0.0
info:
  title: Stef-Chefan
  version: '1.0'
servers:
  - url: 'http://localhost:8080'
paths:
  /api/v1/pickups:
    get:
      tags: ['pickups']
      summary: List existing pickups
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pickup'
    post:
      tags: ['pickups']
      summary: Create new pickup
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pickup'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pickup'
  /api/v1/pickups/{pickupID}:
    parameters:
      - $ref : '#/components/parameters/pickupID'
    put:
      tags: ['pickups']
      summary: Update pickup
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pickup'
      responses: 
        '200':
          description: OK
    get:
      tags: ['pickups']
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pickup'

  /api/v1/pickups/{pickupID}/orders:
    parameters:
      - $ref : '#/components/parameters/pickupID'
    get:
      tags: ['pickups']
      summary: List orders of the pickup
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
    post:
      tags: ['pickups']
      summary: Create anorder on the given pickup
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
  /api/v1/pickups/{pickupID}/orders/{orderID}:
    parameters:
      - $ref : '#/components/parameters/pickupID'
      - $ref : '#/components/parameters/orderID'
    put:
      tags: ['pickups']
      summary: Update order
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:         
        '200':
          description: OK
    get:
      tags: ['pickups']
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'

  /api/v1/products:
    get:
      tags: ['products']
      summary: List available products
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
components:
  schemas:
    Product:
      properties:
        id:
          type: string
        name:
          type: string
        price:
          type: string
        ingredients:
          type: array
          items:
            type: string
      required:
        - id
    OrderItem:
      properties:
        product:
          $ref: '#/components/schemas/Product'
        count:
          type: integer
        comment:
          type: string
      required:
        - product
        - count
    Order:
      properties:
        id:
          type: string
        eater:
          type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
        price:
          type: string
        payed:
          type: boolean
      required:
        - eater
        - items
    Pickup:
      properties:
        id:
          type: string
          format: uuid
        picker:
          type: string
        date:
          type: string
          format: date
        status:
          type: string
      required:
        - picker
        - date
  parameters:
    pickupID:
      name: pickupID
      in: path
      required: true
      schema:
        type: string
    orderID:
      name: orderID
      in: path
      required: true
      schema:
        type: string
